import SwiftUI
import Combine

enum AppLanguage: String, CaseIterable, Identifiable {
    case chinese = "zh"
    case english = "en"
    case indonesian = "id"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .chinese: return "中文"
        case .english: return "English"
        case .indonesian: return "Bahasa Indonesia"
        }
    }
}

final class AppSettings: ObservableObject {
    static let shared = AppSettings()

    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: "appLanguage")
        }
    }

    @Published var fontScale: Double {
        didSet {
            let normalized = AppSettings.normalizeFontScale(fontScale)
            if normalized != fontScale {
                fontScale = normalized
                return
            }
            UserDefaults.standard.set(fontScale, forKey: "appFontScale")
        }
    }

    @Published var patientName: String {
        didSet {
            UserDefaults.standard.set(patientName, forKey: "patientName")
        }
    }

    @Published var patientAge: Int {
        didSet {
            UserDefaults.standard.set(patientAge, forKey: "patientAge")
        }
    }

    @Published var patientGenderKey: String {
        didSet {
            UserDefaults.standard.set(patientGenderKey, forKey: "patientGenderKey")
        }
    }

    @Published var patientNotes: String {
        didSet {
            UserDefaults.standard.set(patientNotes, forKey: "patientNotes")
        }
    }

    @Published var weeklyReminderThreshold: Int {
        didSet {
            UserDefaults.standard.set(weeklyReminderThreshold, forKey: "weeklyReminderThreshold")
        }
    }

    @Published var weeklyBanThreshold: Int {
        didSet {
            UserDefaults.standard.set(weeklyBanThreshold, forKey: "weeklyBanThreshold")
        }
    }

    @Published var scheduleWarningThreshold: Int {
        didSet {
            UserDefaults.standard.set(scheduleWarningThreshold, forKey: "scheduleWarningThreshold")
        }
    }

    @Published var autoEmailReminderEnabled: Bool {
        didSet {
            UserDefaults.standard.set(autoEmailReminderEnabled, forKey: "autoEmailReminderEnabled")
        }
    }

    private init() {
        let storedLanguage = UserDefaults.standard.string(forKey: "appLanguage") ?? AppLanguage.chinese.rawValue
        language = AppLanguage(rawValue: storedLanguage) ?? .chinese
        let storedFontScale = UserDefaults.standard.double(forKey: "appFontScale")
        fontScale = storedFontScale == 0 ? 1.0 : storedFontScale
        patientName = UserDefaults.standard.string(forKey: "patientName") ?? "王小明"
        patientAge = UserDefaults.standard.object(forKey: "patientAge") as? Int ?? 72
        patientGenderKey = UserDefaults.standard.string(forKey: "patientGenderKey") ?? "home.gender.female"
        patientNotes = UserDefaults.standard.string(forKey: "patientNotes") ?? ""
        weeklyReminderThreshold = UserDefaults.standard.object(forKey: "weeklyReminderThreshold") as? Int ?? 5
        weeklyBanThreshold = UserDefaults.standard.object(forKey: "weeklyBanThreshold") as? Int ?? 6
        scheduleWarningThreshold = UserDefaults.standard.object(forKey: "scheduleWarningThreshold") as? Int ?? 3
        autoEmailReminderEnabled = UserDefaults.standard.object(forKey: "autoEmailReminderEnabled") as? Bool ?? false
    }

    func localized(_ key: String) -> String {
        translations[language]?[key] ?? key
    }

    static func normalizeFontScale(_ rawScale: Double) -> Double {
        guard rawScale.isFinite else { return 1.0 }
        return min(max(rawScale, 0.5), 2.0)
    }

    func scaledFont(_ size: CGFloat, weight: Font.Weight = .regular) -> Font {
        let scale = CGFloat(AppSettings.normalizeFontScale(fontScale))
        let computedSize = size * scale
        let finalSize = min(max(computedSize, 8), 160)
        return Font.system(size: finalSize, weight: weight)
    }

    private let translations: [AppLanguage: [String: String]] = [
        .chinese: [
            "home.title": "朝夕安Always Assurance",
            "home.subtitle": "術後康復生理監測與健康資料儀表板",
            "home.theme": "主題",
            "home.system": "系統",
            "home.light": "淺色",
            "home.dark": "深色",
            "home.settings": "設定",
            "home.fontSize": "字體大小",
            "home.language": "介面語言",
            "home.changeLanguageTitle": "確認切換語言",
            "home.changeLanguageMessage": "確認要將語言切換為 %@ 嗎？",
            "home.healthDashboard": "HealthKit 儀表板",
            "home.scheduleBoard": "照護排班看板",
            "home.handoff": "智慧翻譯交班手冊",
            "home.thermometer": "溫度監測",
            "home.oximeter": "血氧監測",
            "home.bloodPressure": "血壓監測",
            "home.profileTitle": "家人資料",
            "home.primaryCaregivers": "主要照顧者",
            "home.addCaregiver": "新增照顧者",
            "home.caregiverName": "照顧者稱呼",
            "home.caregiverAvailability": "可照護時段",
            "home.noCaregivers": "尚未新增照顧者，請先新增主要照顧者資料。",
            "home.patientName": "家人姓名",
            "home.patientAge": "家人年齡",
            "home.patientGender": "性別",
            "home.patientNotes": "備註",
            "home.patientNotesPlaceholder": "紀錄忌口 過敏 生活習慣等...",
            "home.edit": "編輯",
            "home.cancel": "取消",
            "home.save": "儲存",
            "home.alerts": "異常警示",
            "home.patientDashboard": "家人健康儀表板",
            "home.gender.female": "女性",
            "home.gender.male": "男性",
            "home.gender.other": "其他",
            "home.latestRecords": "最新紀錄",
            "home.noAlerts": "無異常",
            "home.ok": "確定",
            "home.scheduleMissingWarningTitle": "排班缺口提醒",
            "home.scheduleMissingWarningMessage": "未來幾天內偵測到尚未排班的日子，請儘速排班並通知所有照顧者。",
            "home.scheduleGapWarningTitle": "排班空窗提醒",
            "home.appointmentAssignmentWarningTitle": "就診任務未分派",
            "home.appointmentAssignmentWarningMessage": "掃描到的就診任務尚未分派給當時時段的照護者，請至排班看板完成指派。",
            "home.unassignedShiftWarningTitle": "尚有未指派班次",
            "home.unassignedShiftWarningMessage": "目前共有 %d 個未指派的班次，請至排班看板指派照顧者。",
            "home.viewScheduleBoard": "前往排班看板",
            "home.viewTrendCharts": "查看趨勢圖",
            "home.viewCharts": "查看圖表",
            "health.title": "術後康復生理追蹤",
            "health.subtitle": "整合血氧、體溫、血壓，並自動標記異常數值。",
            "health.authorized": "已授權 HealthKit 讀取生理資料",
            "health.notAuthorized": "HealthKit 尚未授權",
            "health.requestAuthorization": "授權 HealthKit",
            "health.authMessage": "請授權應用程式讀取術後生理資料，才能啟用智能異常提醒。",
            "health.refreshData": "重新讀取最新數據",
            "health.anomalyAlert": "異常提醒",
            "health.policyTitle": "資料安全說明",
            "health.policyBody": "本應用僅讀取 HealthKit 授權資料，不會寫入醫療紀錄。所有敏感生理資訊僅儲存在使用者裝置，並在需要時才顯示給當班照護者。",
            "health.metric.oxygen": "血氧 (SpO2)",
            "health.metric.temperature": "體溫",
            "health.metric.systolic": "收縮壓",
            "health.metric.diastolic": "舒張壓",
            "health.metric.oxygenWarning": "血氧低於 93% 需要注意呼吸狀況",
            "health.metric.temperatureWarning": "體溫高於 38.5°C 可能代表感染或發炎",
            "health.metric.systolicWarning": "高血壓狀態可能需要調整照護強度",
            "health.metric.diastolicWarning": "血壓異常建議立即通知班次照護者",
            "health.uploadData": "上傳監測資料",
            "health.uploadResult": "上傳結果",
            "health.uploadSuccess": "監測資料已成功上傳。",
            "health.uploadFailed": "監測資料上傳失敗。",
            "health.uploadError": "上傳錯誤：%@",
            "health.uploadFailedStatus": "上傳失敗，狀態碼：%@",
            "health.uploadUnknownError": "無法確認上傳結果。",
            "health.scanAppointment": "掃描就診憑證",
            "health.selectImageSource": "選擇圖片來源",
            "health.takePhoto": "拍照",
            "health.choosePhoto": "從相簿選擇",
            "health.ocrFailed": "OCR 失敗",
            "health.ocrNoText": "未識別到文字，請重試",
            "health.ocrInvalidImage": "無效圖片，請重試。",
            "health.selectCaregiver": "選擇照顧者",
            "health.selectCaregiverTitle": "選擇照顧者與排班",
            "health.externalHelper": "外傭",
            "health.addToSchedule": "加入照護排班看板",
            "health.appointmentCreated": "已建立就診提醒",
            "health.appointmentAdded": "已將就診加入照護排班，請至排班看板選擇日期：%@",
            "health.appointmentAddedRecurring": "已加入 %d 個就診排班，首次日期：%@",
            "health.appointmentNotAdded": "已建立就診提醒，但未加入排班。",
            "health.appointmentUnassignedWarning": "尚未指派主要照顧者，請至排班看板完成指派。",
            "health.externalContactRequired": "請輸入 Email 或電話以聯繫外傭。",
            "health.appointmentShiftRole": "複診安排",
            "health.appointmentTaskSummary": "就診地點：%@",
            "health.appointmentLocationUnknown": "未知就診地點",
            "appointment.review.title": "確認就診資訊",
            "appointment.review.subtitle": "已從掃描自動填入時間與任務摘要，請確認並補上其餘排班資訊。",
            "appointment.review.scannedText": "掃描內容",
            "appointment.review.detailsSection": "時間與重複頻率",
            "appointment.review.summarySection": "任務摘要與備註",
            "appointment.review.contactSection": "指派對象與聯絡資訊",
            "appointment.review.noDateDetected": "未偵測到日期或時間，請手動設定。",
            "appointment.review.suggestedTaskSummary": "陪同就診",
            "appointment.review.taskSummaryPlaceholder": "任務摘要，例如：台大醫院 — 心臟內科 (僅顯示前往地點與科別)",
            "appointment.review.notePlaceholder": "備註（可留空）",
            "appointment.review.rolePlaceholder": "班別類型，例如：陪診",
            "health.departmentLabel": "科別：",
            "health.noValidData": "沒有有效的健康資料可供上傳。",
            "schedule.title": "多人協作排班與交班一覽",
            "schedule.subtitle": "即時檢視未來輪班、任務摘要與交班備註。",
            "schedule.gap.title": "照護空窗警示",
            "schedule.gap.action": "查詢家居照顧及志願服務隊",
            "schedule.signIn.title": "簽到提醒",
            "schedule.addTask": "新增排班任務",
            "schedule.weeklyReminderThreshold": "照顧者一週照顧過多天數提醒",
            "schedule.weeklyBanThreshold": "照顧者一週照顧過多天數封鎖",
            "schedule.weeklyThresholdHelp": "照顧者一週過多天數 — 當同一照顧者達到 X 天時顯示提醒；達到封鎖天數則禁止新增。",
            "schedule.scheduleWarningThreshold": "照顧者缺班天數",
            "schedule.scheduleWarningThresholdHelp": "當在接下來的 X 天內發現照顧者缺班時，首頁會顯示警示。",
            "schedule.thresholdReminderTitle": "排班提醒",
            "schedule.thresholdReminderText": "照顧者一週照顧過多天數提醒：%d 天；照顧者缺班天數：%d 天；照顧者一週照顧過多天數封鎖：%d 天。",
            "schedule.autoEmailReminder": "自動 15 分鐘前 Email 提醒",
            "schedule.autoEmailReminderHelp": "啟用後，系統會在排班開始前 15 分鐘發送 email 提醒，同時按下發送提醒也會發送 email。",
            "schedule.notifyAllCaregivers": "通知所有照顧者",
            "schedule.notifyAllCaregiversSent": "已通知所有具聯絡方式的照顧者。",
            "schedule.emailAlertSubject": "排班缺口提醒",
            "schedule.emailAlertBody": "您好，系統偵測到未來排班缺口：%@。請儘速補上排班並確認分工。",
            "schedule.careHoursTitle": "每日照護時段",
            "schedule.careHoursDescription": "設定每日需要照護的時段，非照護時段將不會被視為未安排空窗。",
            "schedule.careWindowLabel": "時段",
            "schedule.addCareWindow": "新增時段",
            "schedule.careStartTime": "開始時間",
            "schedule.careEndTime": "結束時間",
            "schedule.careHoursInvalid": "結束時間需晚於開始時間。",
            "schedule.dateSpecificCareHoursTitle": "指定日子的照護時段",
            "schedule.dateSpecificCareHoursDescription": "設定特定日期的照護時段，會覆蓋該日期的每日照護時段設定。",
            "schedule.addDateSpecificCareWindow": "新增指定日期時段",
            "schedule.selectDate": "選擇日期",
            "schedule.settings": "排班設定",
            "schedule.manageCaregivers": "新增照顧者",
            "schedule.assignee.notAssigned": "未指派（待處理）",
            "schedule.assignee.needCaregivers": "尚未建立任何照顧者。請先到「個人資料」新增照顧者，或點下方按鈕新增。",
            "schedule.openCaregiverManager": "新增照顧者",
            "schedule.close": "關閉",
            "schedule.addButton": "新增排班",
            "schedule.noTasks": "今日無排班任務",
            "schedule.unassigned.title": "尚未安排時段",
            "schedule.unassigned.description": "以下時間尚未安排排班：",
            "schedule.calendar": "月曆檢視",
            "schedule.todayMeasurements": "當日量測",
            "schedule.temperature": "體溫：",
            "schedule.spo2": "血氧：",
            "schedule.bloodPressureMeasurement": "血壓：",
            "schedule.todayShifts": "當日排班",
            "schedule.editTask": "編輯任務",
            "schedule.cancel": "取消",
            "schedule.save": "儲存",
            "schedule.confirmDelete": "確認刪除任務",
            "schedule.confirmDeleteMessage": "是否確定刪除此任務？",
            "schedule.delete": "刪除",
            "schedule.complete": "標記完成",
            "schedule.signIn": "簽到",
            "schedule.cancelSignIn": "取消簽到",
            "schedule.assign": "標記指派",
            "schedule.selectPrimaryCaregiver": "選擇主要照顧者",
            "schedule.noteLabel": "備註：",
            "schedule.timeLabel": "時間：",
            "schedule.recurrenceLabel": "重複排班",
            "schedule.recurrence.none": "不重複（單次排班）",
            "schedule.recurrence.daily": "每天",
            "schedule.recurrence.monthly": "每月的今天",
            "schedule.recurrence.yearly": "每年每月的今天",
            "schedule.filter.title": "顯示範圍",
            "schedule.filter.selectedDay": "所選日期",
            "schedule.filter.week": "未來一週",
            "schedule.filter.month": "未來一個月",
            "schedule.filter.year": "未來一年",
            "schedule.filter.all": "全部",
            "schedule.filter.countTemplate": "%@（共 %d 個排班）",
            "schedule.startTime": "開始時間",
            "schedule.endTime": "結束時間",
            "schedule.editTitle": "編輯排班",
            "schedule.export": "匯入行事曆",
            "schedule.exportSuccess": "排班已成功匯入行事曆。",
            "schedule.exportFailure": "匯入行事曆失敗：%@",
            "schedule.importCalendar": "匯入行事曆",
            "schedule.importCompleted": "排班已成功匯入行事曆。",
            "schedule.calendarTitle": "月曆檢視",
            "schedule.taskRole": "班別類型",
            "schedule.selectCaregiver": "選擇照顧者",
            "schedule.selectCaregiverWindow": "選擇時段",
            "schedule.customTimeWindow": "自訂時段",
            "schedule.customCaregiver": "自訂照顧者",
            "schedule.assigneePlaceholder": "指派對象，例如：印尼看護",
            "schedule.emailPlaceholder": "聯絡電子郵件",
            "schedule.phonePlaceholder": "聯絡電話",
            "schedule.taskSummaryPlaceholder": "任務摘要，例如：下午 3 點餵藥、換藥",
            "schedule.notePlaceholder": "備註 / 交班要點",
            "schedule.emailLabel": "Email：",
            "schedule.phoneLabel": "電話：",
            "schedule.sendEmail": "發送 Email",
            "schedule.sendSMS": "發送簡訊",
            "schedule.shareSchedule": "分享排班",
            "schedule.shareEmpty": "目前尚無排班可分享。",
            "schedule.shareTitle": "排班摘要",
            "schedule.sendReminder": "發送提醒",
            "schedule.signedIn": "已簽到",
            "schedule.notSignedIn": "尚未簽到",
            "schedule.backupNotificationTitle": "照護空窗備援媒合",
            "schedule.backupNotificationBody": "系統建議啟動在地 NGO 或第三方照護員支援，請立即聯繫協助。",
            "schedule.noData": "無資料",
            "schedule.gapAlertMessage": "未來 48 小時內偵測到照護空窗，總計約 %d 小時，請儘速補上班次或啟動備援。",
            "schedule.missingSignInMessage": "有 %d 個即將開始的班次尚未簽到，請提醒當值照護者簽到。",
            "schedule.assignmentBlockedMessage": "%@ 本週排班已達 %d 天，無法再新增班次。請調整其他人員或更改日期。",
            "schedule.upcomingScheduleWarning": "未來 %d 天內發現未排班日期：%@。請盡快補排並通知照顧者。",
            "schedule.status.unassigned": "待指派",
            "schedule.status.assigned": "已指派",
            "schedule.status.completed": "已完成",
            "schedule.completionMessages": "太棒了！任務已經順利完成，謝謝你！|很讚！你的努力已經生效，這個排程已完成。|完成了！感謝你的用心照顧和即時回報。|任務完成囉，真是辛苦你了！|已經標記完成，謝謝你讓一切更安心。|好的，這項工作已經完成，繼續保持！|成功完成！你的付出很重要。|已完成，感謝你的細心和迅速處理。|任務已記錄為完成，謝謝你！|優秀！這一筆已完成，感謝你。",
            "schedule.completionSubtitle": "謝謝您的付出，任務已標記完成！",
            "schedule.completionFallback": "完成了！謝謝你的努力！",
            "schedule.homecareNotFound": "找不到 homecare.html",
            "schedule.homecareNotFoundDesc": "請確認該檔案已加入專案並設定為 target resource。",
            "schedule.defaultRole": "照護",
            "schedule.unspecifiedAssignee": "未指定",
            "schedule.emptyTaskSummary": "未填寫內容",
            "schedule.reminderMessage": "您好，提醒您：\n%@\n時間：%@ - %@",
            "schedule.reminderSubject": "排班提醒",
            "schedule.shareFormat": "負責人：%@\n時間：%@ - %@\n任務：%@\n備註：%@\nEmail：%@\n電話：%@",
            "schedule.autoReminderBody": "%@ 的班次將於 15 分鐘後開始，請確認已發送排班提醒。",
            "schedule.dailyScheduleTitle": "今日排班：00:00 - 23:59",
            "schedule.dailyCareWindowsLabel": "每日重覆時段：%@",
            "schedule.overbookedWarning": "%@ 已排班 %d 天，請刪除或更改一天",
            "schedule.weekday.sun": "日",
            "schedule.weekday.mon": "一",
            "schedule.weekday.tue": "二",
            "schedule.weekday.wed": "三",
            "schedule.weekday.thu": "四",
            "schedule.weekday.fri": "五",
            "schedule.weekday.sat": "六",
            "schedule.thresholdDaysSuffix": "%d 天",
            "handoff.title": "跨語言交班與即時翻譯",
            "handoff.subtitle": "輸入中文或錄音，系統會自動產生外傭母語版本與中文回報摘要。",
            "handoff.targetLanguage": "翻譯目標語言：",
            "handoff.contentLabel": "交班內容 / 待辦事項",
            "handoff.createNote": "建立交班紀錄",
            "handoff.startRecording": "語音轉文字",
            "handoff.stopRecording": "停止錄音",
            "handoff.translating": "翻譯中...請稍候",
            "handoff.preview": "翻譯預覽",
            "handoff.sourceLanguage": "來源語言：",
            "handoff.noTranslation": "尚未進行翻譯，請輸入文字或錄音後點選建立交班紀錄。",
            "handoff.log": "交班日誌",
            "handoff.noNotes": "目前尚無交班紀錄。",
            "handoff.original": "原文：",
            "handoff.translated": "翻譯：",
            "handoff.confirmed": "已確認",
            "handoff.deleteNote": "刪除",
            "handoff.pending": "待確認",
            "handoff.markReported": "標記已回報",
            "handoff.reported": "已完成回報",
            "device.bloodPressure.title": "血壓計",
            "device.oximeter.title": "血氧計",
            "device.thermometer.title": "耳溫槍",
            "device.connectionStatus": "連線狀態",
            "device.pairing": "配對中",
            "device.pair": "配對",
            "device.connect": "連線",
            "device.disconnect": "斷線",
            "device.saveData": "儲存資料",
            "device.viewChart": "查看圖表",
            "device.reading": "讀取數值",
            "device.systolic": "收縮壓",
            "device.diastolic": "舒張壓",
            "device.pulse": "脈搏",
            "device.pressure": "壓力",
            "device.status": "狀態",
            "device.battery": "電量",
            "device.noValidData": "沒有有效數據可以儲存",
            "device.saveResult": "儲存結果",
            "device.understood": "了解",
            "device.saveError": "儲存錯誤",
            "device.saveFailedStatus": "儲存失敗，狀態碼：%@",
            "device.unexpectedResponse": "意外回應",
            "device.upload.idle": "尚未上傳",
            "device.upload.uploading": "上傳中...",
            "device.upload.lastSuccess": "上次成功：%@",
            "device.upload.failed": "上傳失敗",
            "common.connectionStatus": "連線狀態",
            "common.connected": "已連線",
            "common.pairing": "配對中",
            "common.paired": "已配對",
            "common.notPaired": "未配對",
            "common.saving": "儲存中",
            "common.viewChart": "查看圖表",
            "common.viewDataCharts": "查看數據圖表",
            "common.bloodPressureReading": "血壓讀數",
            "common.measurementComplete": "量測完成",
            "common.readyToMeasure": "準備量測",
            "common.disconnected": "已斷線",
            "common.status": "狀態",
            "common.pressure": "壓力",
            "common.temperature": "體溫",
            "common.spO2": "SpO2",
            "common.heartRate": "心率",
            "common.battery": "電量",
            "common.measurementStatus": "量測狀態",
            "common.mode": "模式",
            "common.type": "類型",
            "common.value": "數值",
            "common.startPairing": "開始配對",
            "common.stopPairing": "停止配對",
            "common.cancel": "取消",
            "common.ok": "確定",
            "chart.loading": "資料載入中...",
            "chart.noData": "無可用資料",
            "chart.bloodPressureHistory": "血壓趨勢",
            "chart.bloodPressureTitle": "血壓歷史記錄",
            "chart.thermometerTitle": "溫度歷史記錄",
            "chart.oximeterTitle": "血氧數據圖表",
            "chart.spO2HeartRate": "SpO2 與心率",
            "chart.perfusionIndex": "灌注指數 (PI)",
            "chart.pi": "PI",
            "chart.piValue": "PI 數值",
            "chart.unknownServerError": "伺服器發生未知錯誤",
            "chart.value": "數值",
            "chart.time": "時間",
            "unit.bpm": "BPM",
            "unit.mmHg": "mmHg",
            "unit.celsius": "°C",
            "reference.bloodPressure": "血壓 120/80 mmHg",
            "reference.temperature": "溫度 36.0-37.2 °C",
            "reference.oxygen": "血氧 95%-100%"
        ],
        .english: [
            "home.title": "朝夕安Always Assurance",
            "home.subtitle": "Postoperative recovery monitoring and health dashboard",
            "home.theme": "Theme",
            "home.system": "System",
            "home.light": "Light",
            "home.dark": "Dark",
            "home.settings": "Settings",
            "home.fontSize": "Font Size",
            "home.language": "Language",
            "home.changeLanguageTitle": "Change Language",
            "home.changeLanguageMessage": "Are you sure you want to change the language to %@?",
            "home.healthDashboard": "HealthKit Dashboard",
            "home.scheduleBoard": "Care Schedule Board",
            "home.handoff": "Smart translation handover manual",
            "home.thermometer": "Thermometer",
            "home.oximeter": "Oximeter",
            "home.bloodPressure": "Blood Pressure",
            "home.profileTitle": "Patient profile",
            "home.primaryCaregivers": "Primary caregivers",
            "home.addCaregiver": "Add caregiver",
            "home.caregiverName": "Caregiver name",
            "home.caregiverAvailability": "Available windows",
            "home.noCaregivers": "No primary caregivers yet. Add one to simplify scheduling.",
            "home.patientName": "Patient name",
            "home.patientAge": "Patient age",
            "home.patientGender": "Gender",
            "home.patientNotes": "Notes",
            "home.patientNotesPlaceholder": "Record dietary restrictions, allergies, habits...",
            "home.edit": "Edit",
            "home.cancel": "Cancel",
            "home.save": "Save",
            "home.alerts": "Alerts",
            "home.patientDashboard": "Patient Dashboard",
            "home.gender.female": "Female",
            "home.gender.male": "Male",
            "home.gender.other": "Other",
            "home.latestRecords": "Latest records",
            "home.noAlerts": "No alerts",
            "home.ok": "OK",
            "home.scheduleMissingWarningTitle": "Schedule coverage warning",
            "home.scheduleMissingWarningMessage": "A missing schedule was detected for upcoming days. Please fill shifts and notify caregivers.",
            "home.scheduleGapWarningTitle": "Schedule gap warning",
            "home.appointmentAssignmentWarningTitle": "Appointment task needs assignment",
            "home.appointmentAssignmentWarningMessage": "A scanned appointment task has not yet been assigned to a caregiver for the appointment time. Please assign it in the schedule board.",
            "home.unassignedShiftWarningTitle": "Unassigned shifts",
            "home.unassignedShiftWarningMessage": "%d shift(s) are still unassigned. Tap to open the schedule board and assign a caregiver.",
            "home.viewScheduleBoard": "View schedule board",
            "home.viewTrendCharts": "View trend charts",
            "home.viewCharts": "View charts",
            "health.title": "Postoperative vital tracking",
            "health.subtitle": "Combines oxygen, temperature, and blood pressure with automatic alert detection.",
            "health.authorized": "HealthKit authorization granted",
            "health.notAuthorized": "HealthKit is not authorized",
            "health.requestAuthorization": "Authorize HealthKit",
            "health.authMessage": "Please authorize the app to read postoperative health data to enable smart alerts.",
            "health.refreshData": "Reload latest data",
            "health.anomalyAlert": "Anomaly Alert",
            "health.policyTitle": "Data safety",
            "health.policyBody": "This app only reads authorized HealthKit data and does not write medical records. Sensitive vital information stays on the device and is shown only to the current caregiver.",
            "health.metric.oxygen": "Oxygen (SpO2)",
            "health.metric.temperature": "Temperature",
            "health.metric.systolic": "Systolic",
            "health.metric.diastolic": "Diastolic",
            "health.metric.oxygenWarning": "Oxygen below 93% requires attention to breathing.",
            "health.metric.temperatureWarning": "Temperature above 38.5°C may indicate infection or inflammation.",
            "health.metric.systolicWarning": "High blood pressure may require adjusting care intensity.",
            "health.metric.diastolicWarning": "Abnormal blood pressure should be reported to the caregiver immediately.",
            "health.uploadData": "Upload monitoring data",
            "health.uploadResult": "Upload result",
            "health.uploadSuccess": "Monitoring data uploaded successfully.",
            "health.uploadFailed": "Monitoring data upload failed.",
            "health.uploadError": "Upload error: %@",
            "health.uploadFailedStatus": "Upload failed with status: %@",
            "health.uploadUnknownError": "Unable to confirm upload result.",
            "health.scanAppointment": "Scan appointment document",
            "health.selectImageSource": "Choose image source",
            "health.takePhoto": "Take photo",
            "health.choosePhoto": "Choose from library",
            "health.ocrFailed": "OCR failed",
            "health.ocrNoText": "No text recognized. Please try again.",
            "health.ocrInvalidImage": "Invalid image. Please try again.",
            "health.selectCaregiver": "Select caregiver",
            "health.selectCaregiverTitle": "Select caregiver and scheduling",
            "health.externalHelper": "External helper",
            "health.addToSchedule": "Add to care schedule board",
            "common.cancel": "Cancel",
            "common.ok": "OK",
            "health.appointmentCreated": "Appointment reminder created",
            "health.appointmentAdded": "Appointment added to care schedule. Open the schedule board on: %@",
            "health.appointmentAddedRecurring": "Added %d appointments. First date: %@",
            "health.appointmentNotAdded": "Appointment reminder created, but not added to schedule.",
            "health.appointmentUnassignedWarning": "No primary caregiver assigned yet. Please assign it in the schedule board.",
            "health.externalContactRequired": "Please enter email or phone for external helper.",
            "health.appointmentShiftRole": "Follow-up appointment",
            "health.appointmentTaskSummary": "Location: %@",
            "health.appointmentLocationUnknown": "Unknown location",
            "appointment.review.title": "Confirm appointment details",
            "appointment.review.subtitle": "Time and task summary have been pre-filled from the scan. Please confirm and complete the remaining shift information.",
            "appointment.review.scannedText": "Scanned text",
            "appointment.review.detailsSection": "Time & frequency",
            "appointment.review.summarySection": "Task summary & notes",
            "appointment.review.contactSection": "Assignee & contact",
            "appointment.review.noDateDetected": "No date or time was detected. Please set it manually.",
            "appointment.review.suggestedTaskSummary": "Accompany to appointment",
            "appointment.review.taskSummaryPlaceholder": "Task summary — place and specialist clinic only, e.g. NTU Hospital — Cardiology",
            "appointment.review.notePlaceholder": "Notes (optional)",
            "appointment.review.rolePlaceholder": "Shift role, e.g. companion visit",
            "health.departmentLabel": "Department: ",
            "health.noValidData": "No valid health data to upload.",
            "schedule.title": "Collaborative care scheduling",
            "schedule.subtitle": "View upcoming shifts, task summaries, and handover notes in real time.",
            "schedule.gap.title": "Care gap alert",
            "schedule.gap.action": "Activate local backup support",
            "schedule.signIn.title": "Sign-in reminder",
            "schedule.addTask": "Add care shift",
            "schedule.weeklyReminderThreshold": "Caregiver weekly overload reminder",
            "schedule.weeklyBanThreshold": "Caregiver weekly overload ban",
            "schedule.weeklyThresholdHelp": "Caregiver weekly overload — show reminder when the same caregiver reaches X days; block new shifts at Y days.",
            "schedule.scheduleWarningThreshold": "Caregiver missing shift days",
            "schedule.scheduleWarningThresholdHelp": "If a caregiver has missing shift coverage in the next X days, the home screen shows a warning.",
            "schedule.thresholdReminderTitle": "Schedule reminder",
            "schedule.thresholdReminderText": "Caregiver weekly overload reminder: %d days; caregiver missing shift days: %d days; caregiver weekly overload ban: %d days.",
            "schedule.autoEmailReminder": "Auto 15-minute email reminders",
            "schedule.autoEmailReminderHelp": "When enabled, the system sends an email reminder 15 minutes before a shift starts, and tapping Send reminder also sends email.",
            "schedule.notifyAllCaregivers": "Notify all caregivers",
            "schedule.notifyAllCaregiversSent": "All caregivers with contact information have been notified.",
            "schedule.emailAlertSubject": "Schedule coverage alert",
            "schedule.emailAlertBody": "Hello, the system detected missing schedule coverage: %@. Please fill the schedule and notify caregivers.",
            "schedule.careHoursTitle": "Daily care windows",
            "schedule.careHoursDescription": "Set the hours each day when care is required. Times outside this window will not count as uncovered gaps.",
            "schedule.careWindowLabel": "Window",
            "schedule.addCareWindow": "Add window",
            "schedule.careStartTime": "Start time",
            "schedule.careEndTime": "End time",
            "schedule.careHoursInvalid": "End time must be later than start time.",
            "schedule.dateSpecificCareHoursTitle": "Date-specific care hours",
            "schedule.dateSpecificCareHoursDescription": "Set care hours for specific dates. These will override the daily care window for that date.",
            "schedule.addDateSpecificCareWindow": "Add date-specific window",
            "schedule.selectDate": "Select date",
            "schedule.settings": "Schedule settings",
            "schedule.manageCaregivers": "Add caregivers",
            "schedule.assignee.notAssigned": "Not assigned (pending)",
            "schedule.assignee.needCaregivers": "No caregivers exist yet. Add a caregiver under Patient Profile, or tap the button below to add one.",
            "schedule.openCaregiverManager": "Add caregivers",
            "schedule.close": "Close",
            "schedule.addButton": "Add shift",
            "schedule.noTasks": "No shifts scheduled today",
            "schedule.unassigned.title": "Unassigned time slots",
            "schedule.unassigned.description": "The following periods have no assigned shifts:",
            "schedule.calendar": "Calendar overview",
            "schedule.todayMeasurements": "Today’s measurements",
            "schedule.temperature": "Temperature:",
            "schedule.spo2": "SpO2:",
            "schedule.bloodPressureMeasurement": "Blood pressure:",
            "schedule.todayShifts": "Today’s shifts",
            "schedule.editTask": "Edit task",
            "schedule.cancel": "Cancel",
            "schedule.save": "Save",
            "schedule.confirmDelete": "Confirm delete",
            "schedule.confirmDeleteMessage": "Are you sure you want to remove this task?",
            "schedule.delete": "Delete",
            "schedule.complete": "Mark complete",
            "schedule.signIn": "Sign in",
            "schedule.cancelSignIn": "Cancel sign in",
            "schedule.assign": "Mark assigned",
            "schedule.selectPrimaryCaregiver": "Select primary caregiver",
            "schedule.noteLabel": "Note:",
            "schedule.timeLabel": "Time:",
            "schedule.recurrenceLabel": "Recurrence",
            "schedule.recurrence.none": "No repeat (single shift)",
            "schedule.recurrence.daily": "Daily",
            "schedule.recurrence.monthly": "Monthly on this day",
            "schedule.recurrence.yearly": "Yearly on this date",
            "schedule.filter.title": "Show shifts",
            "schedule.filter.selectedDay": "Selected day",
            "schedule.filter.week": "Next 7 days",
            "schedule.filter.month": "Next 30 days",
            "schedule.filter.year": "Next 365 days",
            "schedule.filter.all": "All",
            "schedule.filter.countTemplate": "%@ (%d shifts)",
            "schedule.startTime": "Start time",
            "schedule.endTime": "End time",
            "schedule.editTitle": "Edit shift",
            "schedule.export": "Export to calendar",
            "schedule.exportSuccess": "Shifts were successfully exported.",
            "schedule.exportFailure": "Failed to export shifts: %@",
            "schedule.importCalendar": "Import calendar",
            "schedule.importCompleted": "Shifts were successfully imported.",
            "schedule.calendarTitle": "Calendar view",
            "schedule.taskRole": "Shift type",
            "schedule.selectCaregiver": "Select caregiver",
            "schedule.selectCaregiverWindow": "Select window",
            "schedule.customTimeWindow": "Custom window",
            "schedule.customCaregiver": "Custom caregiver",
            "schedule.assigneePlaceholder": "Assignee, e.g. Indonesian caregiver",
            "schedule.emailPlaceholder": "Contact email",
            "schedule.phonePlaceholder": "Contact phone",
            "schedule.taskSummaryPlaceholder": "Task summary, e.g. medication at 3pm, dressing change",
            "schedule.notePlaceholder": "Notes / handover details",
            "schedule.emailLabel": "Email: ",
            "schedule.phoneLabel": "Phone: ",
            "schedule.sendEmail": "Send Email",
            "schedule.sendSMS": "Send SMS",
            "schedule.shareSchedule": "Share schedule",
            "schedule.shareEmpty": "No schedule items available to share.",
            "schedule.shareTitle": "Care schedule summary",
            "schedule.sendReminder": "Send reminder",
            "schedule.signedIn": "Signed in",
            "schedule.notSignedIn": "Not signed in",
            "schedule.backupNotificationTitle": "Care coverage gap alert",
            "schedule.backupNotificationBody": "The system recommends activating local backup support now for uninterrupted care.",
            "schedule.noData": "No data",
            "schedule.gapAlertMessage": "A care gap of about %d hour(s) was detected in the next 48 hours. Please fill the shift or activate backup support.",
            "schedule.missingSignInMessage": "%d upcoming shift(s) have not signed in. Please remind the on-duty caregivers to sign in.",
            "schedule.assignmentBlockedMessage": "%@ has already reached %d shift days this week and cannot be assigned more. Please pick a different caregiver or date.",
            "schedule.upcomingScheduleWarning": "Found unscheduled days in the next %d day(s): %@. Please fill the schedule and notify caregivers.",
            "schedule.status.unassigned": "Unassigned",
            "schedule.status.assigned": "Assigned",
            "schedule.status.completed": "Completed",
            "schedule.completionMessages": "Awesome! The task has been completed successfully, thank you!|Great job! Your effort paid off, this shift is done.|Done! Thanks for your dedicated care and prompt reporting.|Task completed — you did a great job!|Marked complete, thank you for making everything more reassuring.|All right, this task is done — keep it up!|Successfully completed! Your contribution truly matters.|Completed — thanks for your attention to detail and quick handling.|The task has been recorded as complete, thank you!|Excellent! This one is done, thank you.",
            "schedule.completionSubtitle": "Thank you for your effort — the task has been marked complete!",
            "schedule.completionFallback": "Done! Thanks for your hard work!",
            "schedule.homecareNotFound": "homecare.html not found",
            "schedule.homecareNotFoundDesc": "Please make sure the file is added to the project and set as a target resource.",
            "schedule.defaultRole": "Care",
            "schedule.unspecifiedAssignee": "Unspecified",
            "schedule.emptyTaskSummary": "No content provided",
            "schedule.reminderMessage": "Hello, a reminder:\n%@\nTime: %@ - %@",
            "schedule.reminderSubject": "Shift reminder",
            "schedule.shareFormat": "Assignee: %@\nTime: %@ - %@\nTask: %@\nNote: %@\nEmail: %@\nPhone: %@",
            "schedule.autoReminderBody": "%@'s shift starts in 15 minutes. Please confirm the shift reminder has been sent.",
            "schedule.dailyScheduleTitle": "Today's schedule: 00:00 - 23:59",
            "schedule.dailyCareWindowsLabel": "Daily care windows: %@",
            "schedule.overbookedWarning": "%@ has been scheduled %d day(s) — please remove or change one day",
            "schedule.weekday.sun": "Sun",
            "schedule.weekday.mon": "Mon",
            "schedule.weekday.tue": "Tue",
            "schedule.weekday.wed": "Wed",
            "schedule.weekday.thu": "Thu",
            "schedule.weekday.fri": "Fri",
            "schedule.weekday.sat": "Sat",
            "schedule.thresholdDaysSuffix": "%d day(s)",
            "handoff.title": "Cross-language handover & instant translation",
            "handoff.subtitle": "Enter text or use voice, and the system will create the caregiver’s native version plus a Chinese summary.",
            "handoff.targetLanguage": "Target language:",
            "handoff.contentLabel": "Handover content / tasks",
            "handoff.createNote": "Create handover note",
            "handoff.startRecording": "Voice to text",
            "handoff.stopRecording": "Stop recording",
            "handoff.translating": "Translating... please wait",
            "handoff.preview": "Translation preview",
            "handoff.sourceLanguage": "Source language:",
            "handoff.noTranslation": "No translation yet. Enter text or record then create a note.",
            "handoff.log": "Handover log",
            "handoff.noNotes": "No handover notes yet.",
            "handoff.original": "Original:",
            "handoff.translated": "Translation:",
            "handoff.confirmed": "Confirmed",
            "handoff.deleteNote": "Delete",
            "handoff.pending": "Pending",
            "handoff.markReported": "Mark reported",
            "handoff.reported": "Report completed",
            "device.bloodPressure.title": "Blood Pressure Meter",
            "device.oximeter.title": "Oximeter",
            "device.thermometer.title": "Thermometer",
            "device.connectionStatus": "Connection Status",
            "device.pairing": "Pairing",
            "device.pair": "Pairing",
            "device.connect": "Connect",
            "device.disconnect": "Disconnect",
            "device.saveData": "Save Data",
            "device.viewChart": "View Chart",
            "device.reading": "Reading",
            "device.systolic": "Systolic",
            "device.diastolic": "Diastolic",
            "device.pulse": "Pulse",
            "device.pressure": "Pressure",
            "device.status": "Status",
            "device.battery": "Battery",
            "device.noValidData": "No valid data to save",
            "device.saveResult": "Save Result",
            "device.understood": "OK",
            "device.saveError": "Save Error",
            "device.saveFailedStatus": "Save failed with status: %@",
            "device.unexpectedResponse": "Unexpected Response",
            "device.upload.idle": "Not uploaded",
            "device.upload.uploading": "Uploading...",
            "device.upload.lastSuccess": "Last success: %@",
            "device.upload.failed": "Upload failed",
            "common.connectionStatus": "Connection Status",
            "common.connected": "Connected",
            "common.pairing": "Pairing",
            "common.paired": "Paired",
            "common.notPaired": "Not Paired",
            "common.saving": "Saving",
            "common.viewChart": "View Chart",
            "common.viewDataCharts": "View Data Charts",
            "common.bloodPressureReading": "Blood Pressure Reading",
            "common.measurementComplete": "Measurement complete",
            "common.readyToMeasure": "Ready to measure",
            "common.disconnected": "Disconnected",
            "common.status": "Status",
            "common.pressure": "Pressure",
            "common.temperature": "Temperature",
            "common.spO2": "SpO2",
            "common.heartRate": "Heart Rate",
            "common.battery": "Battery",
            "common.measurementStatus": "Measurement Status",
            "common.mode": "Mode",
            "common.type": "Type",
            "common.value": "Value",
            "common.startPairing": "Start Pairing",
            "common.stopPairing": "Stop Pairing",
            "chart.loading": "Loading data...",
            "chart.noData": "No data available",
            "chart.bloodPressureHistory": "Blood Pressure Trend",
            "chart.bloodPressureTitle": "Blood Pressure History",
            "chart.thermometerTitle": "Thermometer Data History",
            "chart.oximeterTitle": "Oximeter Data Charts",
            "chart.spO2HeartRate": "SpO2 & Heart Rate",
            "chart.perfusionIndex": "Perfusion Index (PI)",
            "chart.pi": "PI",
            "chart.piValue": "PI Value",
            "chart.unknownServerError": "Unknown server error",
            "chart.value": "Value",
            "chart.time": "Time",
            "unit.bpm": "BPM",
            "unit.mmHg": "mmHg",
            "unit.celsius": "°C",
            "reference.bloodPressure": "Blood pressure 120/80 mmHg",
            "reference.temperature": "Temperature 36.0-37.2 °C",
            "reference.oxygen": "Oxygen 95%-100%"
        ],
        .indonesian: [
            "home.title": "朝夕安Always Assurance",
            "home.subtitle": "Pemantauan pemulihan pasca operasi dan dasbor kesehatan",
            "home.theme": "Tema",
            "home.system": "Sistem",
            "home.light": "Terang",
            "home.dark": "Gelap",
            "home.settings": "Pengaturan",
            "home.fontSize": "Ukuran Huruf",
            "home.language": "Bahasa",
            "home.changeLanguageTitle": "Ubah Bahasa",
            "home.changeLanguageMessage": "Apakah Anda yakin ingin mengubah bahasa menjadi %@?",
            "home.healthDashboard": "Dasbor HealthKit",
            "home.scheduleBoard": "Jadwal Perawatan",
            "home.handoff": "Manual terjemahan cerdas serah terima",
            "home.thermometer": "Termometer",
            "home.oximeter": "Oximeter",
            "home.bloodPressure": "Tekanan Darah",
            "home.profileTitle": "Profil pasien",
            "home.primaryCaregivers": "Pengasuh utama",
            "home.addCaregiver": "Tambah pengasuh",
            "home.caregiverName": "Nama pengasuh",
            "home.caregiverAvailability": "Jendela ketersediaan",
            "home.noCaregivers": "Belum ada pengasuh utama. Tambahkan untuk mempermudah penjadwalan.",
            "home.patientName": "Nama pasien",
            "home.patientAge": "Usia pasien",
            "home.patientGender": "Jenis kelamin",
            "home.patientNotes": "Catatan",
            "home.patientNotesPlaceholder": "Catat pantangan makanan, alergi, kebiasaan hidup...",
            "home.edit": "Sunting",
            "home.cancel": "Batal",
            "home.save": "Simpan",
            "home.alerts": "Peringatan",
            "home.patientDashboard": "Dasbor Pasien",
            "home.gender.female": "Perempuan",
            "home.gender.male": "Laki-laki",
            "home.gender.other": "Lainnya",
            "home.latestRecords": "Catatan terbaru",
            "home.noAlerts": "Tidak ada peringatan",
            "home.ok": "OK",
            "home.scheduleMissingWarningTitle": "Peringatan jadwal",
            "home.scheduleMissingWarningMessage": "Terjadi kekurangan jadwal dalam beberapa hari mendatang. Lengkapi shift dan beri tahu pengasuh.",
            "home.scheduleGapWarningTitle": "Peringatan celah jadwal",
            "home.appointmentAssignmentWarningTitle": "Tugas janji temu belum ditugaskan",
            "home.appointmentAssignmentWarningMessage": "Tugas janji temu yang dipindai belum ditugaskan ke pengasuh untuk waktu janji temu. Silakan tetapkan di papan jadwal.",
            "home.unassignedShiftWarningTitle": "Shift belum ditugaskan",
            "home.unassignedShiftWarningMessage": "%d shift masih belum ditugaskan. Ketuk untuk membuka papan jadwal dan menetapkan pengasuh.",
            "home.viewTrendCharts": "Lihat grafik tren",
            "home.viewCharts": "Lihat grafik",
            "health.title": "Pelacakan vital pasca operasi",
            "health.subtitle": "Menggabungkan oksigen, suhu, dan tekanan darah dengan deteksi peringatan otomatis.",
            "health.authorized": "HealthKit diizinkan untuk membaca data vital",
            "health.notAuthorized": "HealthKit belum diizinkan",
            "health.requestAuthorization": "Izinkan HealthKit",
            "health.authMessage": "Silakan izinkan aplikasi membaca data kesehatan pasca operasi untuk mengaktifkan peringatan pintar.",
            "health.refreshData": "Muat ulang data terbaru",
            "health.anomalyAlert": "Peringatan anomali",
            "health.policyTitle": "Keamanan data",
            "health.policyBody": "Aplikasi ini hanya membaca data HealthKit yang diizinkan dan tidak menulis catatan medis. Informasi vital sensitif tetap berada di perangkat dan hanya ditampilkan kepada pengasuh saat bertugas.",
            "health.metric.oxygen": "Oksigen (SpO2)",
            "health.metric.temperature": "Suhu",
            "health.metric.systolic": "Sistolik",
            "health.metric.diastolic": "Diastolik",
            "health.metric.oxygenWarning": "Oksigen di bawah 93% membutuhkan perhatian pernapasan.",
            "health.metric.temperatureWarning": "Suhu di atas 38.5°C dapat menunjukkan infeksi atau peradangan.",
            "health.metric.systolicWarning": "Tekanan darah tinggi mungkin memerlukan penyesuaian intensitas perawatan.",
            "health.metric.diastolicWarning": "Tekanan darah abnormal sebaiknya segera dilaporkan kepada pengasuh.",
            "health.uploadData": "Unggah data pemantauan",
            "health.uploadResult": "Hasil unggah",
            "health.uploadSuccess": "Data pemantauan berhasil diunggah.",
            "health.uploadFailed": "Unggah data pemantauan gagal.",
            "health.uploadError": "Kesalahan unggah: %@",
            "health.uploadFailedStatus": "Unggah gagal dengan status: %@",
            "health.uploadUnknownError": "Tidak dapat memastikan hasil unggah.",
            "health.scanAppointment": "Pindai dokumen janji temu",
            "health.selectImageSource": "Pilih sumber gambar",
            "health.takePhoto": "Ambil foto",
            "health.choosePhoto": "Pilih dari perpustakaan",
            "health.ocrFailed": "OCR gagal",
            "health.ocrNoText": "Tidak ada teks terdeteksi. Silakan coba lagi.",
            "health.ocrInvalidImage": "Gambar tidak valid. Silakan coba lagi.",
            "health.selectCaregiver": "Pilih perawat",
            "health.selectCaregiverTitle": "Pilih perawat dan penjadwalan",
            "health.externalHelper": "Pembantu eksternal",
            "health.addToSchedule": "Tambahkan ke papan jadwal perawatan",
            "common.cancel": "Batal",
            "common.ok": "OK",
            "health.appointmentCreated": "Pengingat janji temu dibuat",
            "health.appointmentAdded": "Janji temu ditambahkan ke jadwal perawatan. Buka papan jadwal pada: %@",
            "health.appointmentAddedRecurring": "Berhasil menambahkan %d janji temu. Tanggal pertama: %@",
            "health.appointmentNotAdded": "Pengingat janji temu dibuat, tetapi tidak ditambahkan ke jadwal.",
            "health.externalContactRequired": "Harap masukkan email atau telepon untuk pembantu eksternal.",
            "health.appointmentShiftRole": "Janji temu tindak lanjut",
            "health.appointmentTaskSummary": "Dokter: %@",
            "health.appointmentLocationUnknown": "Lokasi tidak diketahui",
            "appointment.review.title": "Konfirmasi detail janji temu",
            "appointment.review.subtitle": "Waktu dan ringkasan tugas telah diisi otomatis dari hasil pindai. Mohon konfirmasi dan lengkapi informasi shift lainnya.",
            "appointment.review.scannedText": "Teks hasil pindai",
            "appointment.review.detailsSection": "Waktu & frekuensi",
            "appointment.review.summarySection": "Ringkasan tugas & catatan",
            "appointment.review.contactSection": "Penerima tugas & kontak",
            "appointment.review.noDateDetected": "Tanggal atau waktu tidak terdeteksi. Mohon atur secara manual.",
            "appointment.review.suggestedTaskSummary": "Mendampingi ke janji temu",
            "appointment.review.taskSummaryPlaceholder": "Ringkasan tugas — hanya tempat dan poli spesialis, mis. RS Cipto — Poli Jantung",
            "appointment.review.notePlaceholder": "Catatan (opsional)",
            "appointment.review.rolePlaceholder": "Peran shift, mis. pendamping kunjungan",
            "health.noValidData": "Tidak ada data kesehatan valid untuk diunggah.",
            "schedule.title": "Penjadwalan perawatan kolaboratif",
            "schedule.subtitle": "Lihat shift mendatang, ringkasan tugas, dan catatan serah terima secara real time.",
            "schedule.gap.title": "Peringatan jeda perawatan",
            "schedule.gap.action": "Aktifkan dukungan cadangan lokal",
            "schedule.signIn.title": "Pengingat hadir",
            "schedule.addTask": "Tambah shift perawatan",
            "schedule.weeklyReminderThreshold": "Peringatan kelebihan hari perawat mingguan",
            "schedule.weeklyBanThreshold": "Pemblokiran kelebihan hari perawat mingguan",
            "schedule.weeklyThresholdHelp": "Kelebihan hari perawat mingguan — tampilkan pengingat saat perawat yang sama mencapai X hari; blokir penambahan shift pada Y hari.",
            "schedule.scheduleWarningThreshold": "Hari kekurangan shift perawat",
            "schedule.scheduleWarningThresholdHelp": "Jika ada perawat yang kekurangan shift dalam X hari ke depan, halaman utama akan menampilkan peringatan.",
            "schedule.thresholdReminderTitle": "Peringatan jadwal",
            "schedule.thresholdReminderText": "Peringatan kelebihan hari perawat mingguan: %d hari; hari kekurangan shift perawat: %d hari; pemblokiran kelebihan hari perawat mingguan: %d hari.",
            "schedule.autoEmailReminder": "Pengingat email otomatis 15 menit sebelumnya",
            "schedule.autoEmailReminderHelp": "Saat diaktifkan, sistem akan mengirim email pengingat 15 menit sebelum shift dimulai, dan menekan Kirim pengingat juga akan mengirim email.",
            "schedule.notifyAllCaregivers": "Beritahu semua pengasuh",
            "schedule.notifyAllCaregiversSent": "Semua pengasuh dengan kontak telah diberi tahu.",
            "schedule.emailAlertSubject": "Peringatan kekurangan jadwal",
            "schedule.emailAlertBody": "Halo, sistem mendeteksi kekurangan jadwal: %@. Mohon lengkapi jadwal dan beri tahu pengasuh.",
            "schedule.careHoursTitle": "Jadwal perawatan harian",
            "schedule.careHoursDescription": "Tetapkan jam-jam setiap hari ketika perawatan diperlukan. Waktu di luar jendela ini tidak akan dihitung sebagai celah.",
            "schedule.careWindowLabel": "Jendela",
            "schedule.addCareWindow": "Tambah jendela",
            "schedule.careStartTime": "Waktu mulai",
            "schedule.careEndTime": "Waktu selesai",
            "schedule.careHoursInvalid": "Waktu selesai harus lebih dari waktu mulai.",
            "schedule.dateSpecificCareHoursTitle": "Jadwal perawatan tanggal spesifik",
            "schedule.dateSpecificCareHoursDescription": "Tetapkan waktu perawatan untuk tanggal tertentu. Ini akan menggantikan jadwal perawatan harian untuk tanggal tersebut.",
            "schedule.addDateSpecificCareWindow": "Tambah jendela spesifik tanggal",
            "schedule.selectDate": "Pilih tanggal",
            "schedule.settings": "Pengaturan jadwal",
            "schedule.manageCaregivers": "Tambah pengasuh",
            "schedule.assignee.notAssigned": "Belum ditugaskan (tertunda)",
            "schedule.assignee.needCaregivers": "Belum ada pengasuh. Tambahkan pengasuh di Profil Pasien, atau ketuk tombol di bawah untuk menambahkannya.",
            "schedule.openCaregiverManager": "Tambah pengasuh",
            "schedule.close": "Tutup",
            "schedule.addButton": "Tambah shift",
            "schedule.noTasks": "Tidak ada shift hari ini",
            "schedule.unassigned.title": "Waktu belum dijadwalkan",
            "schedule.unassigned.description": "Periode berikut belum memiliki jadwal:",
            "schedule.calendar": "Tinjauan kalender",
            "schedule.todayMeasurements": "Pengukuran hari ini",
            "schedule.temperature": "Suhu:",
            "schedule.spo2": "SpO2:",
            "schedule.bloodPressureMeasurement": "Tekanan darah:",
            "schedule.todayShifts": "Shift hari ini",
            "schedule.editTask": "Sunting tugas",
            "schedule.cancel": "Batal",
            "schedule.save": "Simpan",
            "schedule.confirmDelete": "Konfirmasi hapus",
            "schedule.confirmDeleteMessage": "Yakin ingin menghapus tugas ini?",
            "schedule.delete": "Hapus",
            "schedule.complete": "Tandai selesai",
            "schedule.signIn": "Masuk",
            "schedule.cancelSignIn": "Batalkan masuk",
            "schedule.assign": "Tandai ditugaskan",
            "schedule.noteLabel": "Catatan:",
            "schedule.timeLabel": "Waktu:",
            "schedule.recurrenceLabel": "Pengulangan",
            "schedule.recurrence.none": "Tidak diulang (shift tunggal)",
            "schedule.recurrence.daily": "Setiap hari",
            "schedule.recurrence.monthly": "Bulanan pada tanggal ini",
            "schedule.recurrence.yearly": "Tahunan pada tanggal ini",
            "schedule.filter.title": "Tampilkan shift",
            "schedule.filter.selectedDay": "Hari terpilih",
            "schedule.filter.week": "7 hari ke depan",
            "schedule.filter.month": "30 hari ke depan",
            "schedule.filter.year": "365 hari ke depan",
            "schedule.filter.all": "Semua",
            "schedule.filter.countTemplate": "%@ (%d shift)",
            "schedule.startTime": "Waktu mulai",
            "schedule.endTime": "Waktu selesai",
            "schedule.editTitle": "Sunting shift",
            "schedule.export": "Ekspor ke kalender",
            "schedule.exportSuccess": "Shift berhasil diekspor.",
            "schedule.exportFailure": "Gagal mengekspor shift: %@",
            "schedule.importCalendar": "Impor kalender",
            "schedule.importCompleted": "Shift berhasil diimpor.",
            "schedule.calendarTitle": "Tampilan kalender",
            "schedule.taskRole": "Tipe shift",
            "schedule.selectCaregiver": "Pilih pengasuh",
            "schedule.selectCaregiverWindow": "Pilih jendela",
            "schedule.customTimeWindow": "Jendela kustom",
            "schedule.customCaregiver": "Pengasuh kustom",
            "schedule.assigneePlaceholder": "Penerima tugas, misal: perawat Indonesia",
            "schedule.emailPlaceholder": "Email kontak",
            "schedule.phonePlaceholder": "Telepon kontak",
            "schedule.taskSummaryPlaceholder": "Ringkasan tugas, misal: obat jam 3 sore, ganti perban",
            "schedule.notePlaceholder": "Catatan / detail serah terima",
            "schedule.emailLabel": "Email: ",
            "schedule.phoneLabel": "Telepon: ",
            "schedule.sendEmail": "Kirim Email",
            "schedule.sendSMS": "Kirim SMS",
            "schedule.shareSchedule": "Bagikan jadwal",
            "schedule.shareEmpty": "Tidak ada jadwal untuk dibagikan.",
            "schedule.shareTitle": "Ringkasan jadwal perawatan",
            "schedule.sendReminder": "Kirim pengingat",
            "schedule.signedIn": "Sudah masuk",
            "schedule.notSignedIn": "Belum masuk",
            "schedule.backupNotificationTitle": "Peringatan celah perawatan",
            "schedule.backupNotificationBody": "Sistem merekomendasikan mengaktifkan dukungan cadangan lokal sekarang untuk perawatan tanpa jeda.",
            "schedule.noData": "Tidak ada data",
            "schedule.gapAlertMessage": "Terdeteksi jeda perawatan sekitar %d jam dalam 48 jam ke depan. Segera lengkapi shift atau aktifkan dukungan cadangan.",
            "schedule.missingSignInMessage": "%d shift yang akan segera dimulai belum melakukan check-in. Mohon ingatkan pengasuh yang bertugas untuk masuk.",
            "schedule.assignmentBlockedMessage": "%@ sudah mencapai %d hari shift minggu ini dan tidak bisa ditambah. Silakan pilih pengasuh atau tanggal lain.",
            "schedule.upcomingScheduleWarning": "Ditemukan hari tanpa jadwal dalam %d hari ke depan: %@. Mohon lengkapi jadwal dan beri tahu pengasuh.",
            "schedule.status.unassigned": "Belum ditugaskan",
            "schedule.status.assigned": "Sudah ditugaskan",
            "schedule.status.completed": "Selesai",
            "schedule.completionMessages": "Luar biasa! Tugas berhasil diselesaikan, terima kasih!|Kerja bagus! Usaha Anda membuahkan hasil, shift ini selesai.|Selesai! Terima kasih atas perawatan dan laporan Anda.|Tugas selesai — Anda sudah bekerja keras!|Sudah ditandai selesai, terima kasih sudah membuat segalanya lebih tenang.|Baik, tugas ini selesai — terus semangat!|Berhasil diselesaikan! Kontribusi Anda sangat berarti.|Selesai — terima kasih atas ketelitian dan penanganan cepat Anda.|Tugas telah dicatat sebagai selesai, terima kasih!|Sangat bagus! Yang ini sudah selesai, terima kasih.",
            "schedule.completionSubtitle": "Terima kasih atas upaya Anda — tugas telah ditandai selesai!",
            "schedule.completionFallback": "Selesai! Terima kasih atas kerja keras Anda!",
            "schedule.homecareNotFound": "homecare.html tidak ditemukan",
            "schedule.homecareNotFoundDesc": "Pastikan file sudah ditambahkan ke proyek dan diatur sebagai sumber daya target.",
            "schedule.defaultRole": "Perawatan",
            "schedule.unspecifiedAssignee": "Belum ditentukan",
            "schedule.emptyTaskSummary": "Belum ada konten",
            "schedule.reminderMessage": "Halo, pengingat:\n%@\nWaktu: %@ - %@",
            "schedule.reminderSubject": "Pengingat shift",
            "schedule.shareFormat": "Penanggung jawab: %@\nWaktu: %@ - %@\nTugas: %@\nCatatan: %@\nEmail: %@\nTelepon: %@",
            "schedule.autoReminderBody": "Shift %@ dimulai dalam 15 menit. Pastikan pengingat shift sudah dikirim.",
            "schedule.dailyScheduleTitle": "Jadwal hari ini: 00:00 - 23:59",
            "schedule.dailyCareWindowsLabel": "Jendela perawatan harian: %@",
            "schedule.overbookedWarning": "%@ sudah dijadwalkan %d hari — silakan hapus atau ubah satu hari",
            "schedule.weekday.sun": "Min",
            "schedule.weekday.mon": "Sen",
            "schedule.weekday.tue": "Sel",
            "schedule.weekday.wed": "Rab",
            "schedule.weekday.thu": "Kam",
            "schedule.weekday.fri": "Jum",
            "schedule.weekday.sat": "Sab",
            "schedule.thresholdDaysSuffix": "%d hari",
            "handoff.title": "Serah terima lintas bahasa & terjemahan instan",
            "handoff.subtitle": "Masukkan teks atau gunakan suara, sistem akan membuat versi bahasa ibu pengasuh dan ringkasan bahasa Mandarin.",
            "handoff.targetLanguage": "Bahasa target:",
            "handoff.contentLabel": "Konten serah terima / tugas",
            "handoff.createNote": "Buat catatan serah terima",
            "handoff.startRecording": "Suara ke teks",
            "handoff.stopRecording": "Berhenti merekam",
            "handoff.translating": "Menerjemahkan... mohon tunggu",
            "handoff.preview": "Pratinjau terjemahan",
            "handoff.sourceLanguage": "Bahasa sumber:",
            "handoff.noTranslation": "Belum ada terjemahan. Masukkan teks atau rekam lalu buat catatan.",
            "handoff.log": "Log serah terima",
            "handoff.noNotes": "Belum ada catatan serah terima.",
            "handoff.original": "Asli:",
            "handoff.translated": "Terjemahan:",
            "handoff.confirmed": "Dikonfirmasi",
            "handoff.deleteNote": "Hapus",
            "handoff.pending": "Menunggu",
            "handoff.markReported": "Tandai dilaporkan",
            "handoff.reported": "Laporan selesai",
            "device.bloodPressure.title": "Meter Tekanan Darah",
            "device.oximeter.title": "Oximeter",
            "device.thermometer.title": "Termometer",
            "device.connectionStatus": "Status Koneksi",
            "device.pairing": "Memasangkan",
            "device.pair": "Memasangkan",
            "device.connect": "Hubungkan",
            "device.disconnect": "Putuskan",
            "device.saveData": "Simpan Data",
            "device.viewChart": "Lihat Grafik",
            "device.reading": "Pembacaan",
            "device.systolic": "Sistolik",
            "device.diastolic": "Diastolik",
            "device.pulse": "Nadi",
            "device.pressure": "Tekanan",
            "device.status": "Status",
            "device.battery": "Baterai",
            "device.noValidData": "Tidak ada data valid untuk disimpan",
            "device.saveResult": "Hasil Penyimpanan",
            "device.understood": "Mengerti",
            "device.saveError": "Kesalahan Penyimpanan",
            "device.saveFailedStatus": "Penyimpanan gagal dengan status: %@",
            "device.unexpectedResponse": "Respons Tidak Terduga",
            "device.upload.idle": "Belum diunggah",
            "device.upload.uploading": "Mengunggah...",
            "device.upload.lastSuccess": "Terakhir berhasil: %@",
            "device.upload.failed": "Pengunggahan gagal",
            "common.connectionStatus": "Status Koneksi",
            "common.connected": "Tersambung",
            "common.pairing": "Memasangkan",
            "common.paired": "Terpasang",
            "common.notPaired": "Belum Terpasang",
            "common.saving": "Menyimpan",
            "common.viewChart": "Lihat Grafik",
            "common.viewDataCharts": "Lihat Data Grafik",
            "common.bloodPressureReading": "Pembacaan Tekanan Darah",
            "common.measurementComplete": "Pengukuran selesai",
            "common.readyToMeasure": "Siap mengukur",
            "common.disconnected": "Terputus",
            "common.status": "Status",
            "common.pressure": "Tekanan",
            "common.temperature": "Suhu",
            "common.spO2": "SpO2",
            "common.heartRate": "Denyut Jantung",
            "common.battery": "Baterai",
            "common.measurementStatus": "Status Pengukuran",
            "common.mode": "Mode",
            "common.type": "Tipe",
            "common.value": "Nilai",
            "common.startPairing": "Mulai Memasangkan",
            "common.stopPairing": "Berhenti Memasangkan",
            "chart.loading": "Memuat data...",
            "chart.noData": "Tidak ada data",
            "chart.bloodPressureHistory": "Tren Tekanan Darah",
            "chart.bloodPressureTitle": "Riwayat Tekanan Darah",
            "chart.thermometerTitle": "Riwayat Data Termometer",
            "chart.oximeterTitle": "Grafik Data Oximeter",
            "chart.spO2HeartRate": "SpO2 & Denyut Jantung",
            "chart.perfusionIndex": "Indeks Perfusi (PI)",
            "chart.pi": "PI",
            "chart.piValue": "Nilai PI",
            "chart.unknownServerError": "Kesalahan server tidak diketahui",
            "chart.value": "Nilai",
            "chart.time": "Waktu",
            "unit.bpm": "BPM",
            "unit.mmHg": "mmHg",
            "unit.celsius": "°C",
            "reference.bloodPressure": "Tekanan darah 120/80 mmHg",
            "reference.temperature": "Suhu 36.0-37.2 °C",
            "reference.oxygen": "Oksigen 95%-100%"
        ]
    ]
}
